### ISSUE TITLE
Implement a hero animation inside the app. 

### ISSUE THREAD

**Issue by dev1abhi** [dev1abhi/Flutter-Animations#11]

**Comment by bidur0123** [comment]
please assign me this issue

**Comment by saurav0523** [comment]
can you please assign me this task

**Comment by dev1abhi** [comment]
hey..thanks for responding but I am working on this issue. You can take any other animation under flutter docs , open up an issue and tag me . I will assign it to you.

**Comment by dev1abhi** [comment]
Implemented and closed.
