### ISSUE TITLE
Naming convention  

### ISSUE THREAD

**Issue by habeebputhiyakath** [dev1abhi/Flutter-Animations#16]
Libraries, packages, directories, and source files name should be in  lowercase_with_underscores

**Comment by dev1abhi** [comment]
thanks for contributing.

**Comment by habeebputhiyakath** [comment]
plz remove the hacktorfest-accepted and  hacktorfest labels

**Comment by habeebputhiyakath** [comment]
next my commit time no add this labels @dev1abhi

**Comment by habeebputhiyakath** [comment]
thanks

**Comment by dev1abhi** [comment]
yeah sure.

> next my commit time no add this labels @dev1abhi
