### ISSUE TITLE
Issue in UI

### ISSUE THREAD

**Issue by Redvey** [dev1abhi/Flutter-Animations#24]
The new options on the menu screen are navigating to a  Animated Dialogbox page .This might happen due to no vertical gap between the new options.
<img width="297" alt="Screenshot 2023-10-19 at 9 01 17 PM" src="https://github.com/dev1abhi/Flutter-Animations/assets/128305006/5f0dcdc3-90ac-4e28-9218-53e176230938">

**Comment by dev1abhi** [comment]
You can work on it's fix , if you like to. Much appreciated.

**Comment by Redvey** [comment]
> You can work on it's fix , if you like to. Much appreciated.

Thank you so much @dev1abhi  I did and also created a pull request as well. Again thank you so much for this opportunity.
