### ISSUE TITLE
Migrate apply Gradle plugin method from Gradle's legacy imperative apply script method to declarative block method

### ISSUE THREAD

**Issue by PiyushJaiswal236** [dev1abhi/Flutter-Animations#31]
This project was built with SDK version prior to 3.16, hence it used this method to apply Flutter's Gradle plugins, so while building debug/release apk  said to migrate 
![image](https://github.com/user-attachments/assets/025416b9-7b05-4d3d-b0a7-bdeff3671041)

Steps to recreate:
1) run flutter build apk 

I would like to fix it so will u accept my PR

**Comment by dev1abhi** [comment]
Sure.Thanks for the contribution.
